version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - networkbridge

  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: myrootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - networkbridge

  backend:
    image: python:3.8
    container_name: python_backend
    environment:
      - FLASK_APP=backend.db
    volumes:
      - ./backend:/backend
    depends_on:
      - postgres
      - mysql
    ports:
      - "5002:5000"
    command: >
      sh -c "pip install psycopg2 mysql-connector-python flask pymysql cryptography && flask run --host=0.0.0.0"
    networks:
      - networkbridge

  frontend:
    depends_on:
      - backend
    image: python:3.8
    environment:
      - FLASK_APP=frontend.front
    container_name: frontend-container
    ports:
      - 5001:5000
    command: sh -c "pip install flask requests && flask run --host=0.0.0.0"
    volumes:
      - ./frontend:/frontend
    networks:
      - networkbridge

volumes:
  postgres_data: 
  mysql_data:
  backend:
  frontend:

networks:
  networkbridge:
    driver: bridge